Repository ICCAS2024-Helper/facialFit-backend, pull requests merged in 2024-06, with the labels that each got.

#3 feature: UserDB 설계
  src/main/java/com/smilehelper/application/domain/User.java
  src/main/java/com/smilehelper/application/dto/UserDTO.java
  src/main/java/com/smilehelper/application/enums/HealthArea.java
  src/main/java/com/smilehelper/application/enums/SeverityLevel.java
  src/main/java/com/smilehelper/application/enums/UserRole.java
  src/main/java/com/smilehelper/application/repository/UserRepository.java
Labels: feature

#5 feature: 로그인, 로그아웃, 회원가입 api 구현
  build.gradle
  src/main/java/com/smilehelper/application/config/security/SecurityConfig.java
  src/main/java/com/smilehelper/application/controller/JoinController.java
  src/main/java/com/smilehelper/application/controller/LoginController.java
  src/main/java/com/smilehelper/application/controller/TestController.java
  src/main/java/com/smilehelper/application/controller/UserController.java
  src/main/java/com/smilehelper/application/domain/User.java
  src/main/java/com/smilehelper/application/dto/JoinDTO.java
  src/main/java/com/smilehelper/application/dto/LoginDTO.java
  src/main/java/com/smilehelper/application/dto/UserDTO.java
  src/main/java/com/smilehelper/application/repository/UserRepository.java
  src/main/java/com/smilehelper/application/security/JwtAuthenticationFilter.java
  src/main/java/com/smilehelper/application/security/JwtTokenProvider.java
  src/main/java/com/smilehelper/application/security/UserAuthentication.java
  src/main/java/com/smilehelper/application/service/JoinService.java
  src/main/java/com/smilehelper/application/service/LoginService.java
  src/main/java/com/smilehelper/application/service/UserService.java
Labels: feature

#7 fix: 배포 위한 도커 파일 수정
  Dockerfile
  Dockerfile/docker-compose.yml
  docker-compose.yml
Labels: fix

#8 fix: 배포 위한 도커 파일 수정
  Dockerfile
Labels: fix

#9 fix: gitignore 수정
  .gitignore
Labels: fix

#10 fix: dockerignore 수정
  .dockerignore
Labels: fix

#11 fix: health check 추가
  build.gradle
Labels: fix

#13 feature: CI/CD 추가
  .github/workflows/ci.yml
Labels: feature

#15 fix: 도커파일 수정
  Dockerfile
  build.gradle
Labels: fix

#16 fix: 도커파일 수정
  Dockerfile
Labels: fix

#19 Feature: Quest 관련 API 개발
  src/main/java/com/smilehelper/application/config/security/SecurityConfig.java
  src/main/java/com/smilehelper/application/controller/JoinController.java
  src/main/java/com/smilehelper/application/controller/LoginController.java
  src/main/java/com/smilehelper/application/controller/QuestController.java
  src/main/java/com/smilehelper/application/controller/UserController.java
  src/main/java/com/smilehelper/application/controller/UserQuestController.java
  src/main/java/com/smilehelper/application/domain/Quest.java
  src/main/java/com/smilehelper/application/domain/User.java
  src/main/java/com/smilehelper/application/domain/UserQuest.java
  src/main/java/com/smilehelper/application/dto/JoinDTO.java
  src/main/java/com/smilehelper/application/dto/QuestDTO.java
  src/main/java/com/smilehelper/application/dto/UserQuestDTO.java
  src/main/java/com/smilehelper/application/enums/QuestType.java
  src/main/java/com/smilehelper/application/exception/QuestException.java
  src/main/java/com/smilehelper/application/exception/UserException.java
  src/main/java/com/smilehelper/application/repository/QuestRepository.java
  src/main/java/com/smilehelper/application/repository/UserQuestRepository.java
  src/main/java/com/smilehelper/application/security/JwtAuthenticationFilter.java
  src/main/java/com/smilehelper/application/security/JwtTokenProvider.java
  src/main/java/com/smilehelper/application/service/JoinService.java
  src/main/java/com/smilehelper/application/service/LoginService.java
  src/main/java/com/smilehelper/application/service/QuestService.java
  src/main/java/com/smilehelper/application/service/UserQuestService.java
  src/main/java/com/smilehelper/application/service/UserService.java
Labels: feature, fix

#21 Item, Purchase API 추가 및 yml 코드 변경
  docker-compose.yml
  src/main/java/com/smilehelper/application/controller/ItemController.java
  src/main/java/com/smilehelper/application/controller/PurchaseController.java
  src/main/java/com/smilehelper/application/domain/Item.java
  src/main/java/com/smilehelper/application/domain/Purchase.java
  src/main/java/com/smilehelper/application/dto/ItemDTO.java
  src/main/java/com/smilehelper/application/dto/PurchaseDTO.java
  src/main/java/com/smilehelper/application/repository/ItemRepository.java
  src/main/java/com/smilehelper/application/repository/PurchaseRepository.java
  src/main/java/com/smilehelper/application/service/ItemService.java
  src/main/java/com/smilehelper/application/service/PurchaseService.java
Labels: feature

#22 Feature: 스토리모드 관련 API 개발
  docker-compose.yml
  src/main/java/com/smilehelper/application/controller/StageController.java
  src/main/java/com/smilehelper/application/controller/UserController.java
  src/main/java/com/smilehelper/application/controller/UserStageProgressController.java
  src/main/java/com/smilehelper/application/domain/Stage.java
  src/main/java/com/smilehelper/application/domain/User.java
  src/main/java/com/smilehelper/application/domain/UserStageProgress.java
  src/main/java/com/smilehelper/application/dto/StageDTO.java
  src/main/java/com/smilehelper/application/dto/UserStageProgressDTO.java
  src/main/java/com/smilehelper/application/exception/StageException.java
  src/main/java/com/smilehelper/application/repository/StageRepository.java
  src/main/java/com/smilehelper/application/repository/UserStageProgressRepository.java
  src/main/java/com/smilehelper/application/service/StageService.java
  src/main/java/com/smilehelper/application/service/UserStageProgressService.java
Labels: feature
